/**
 * App icons = Cloudflare mark from Logo.tsx on transparent background.
 * Usage: node src-tauri/icons/generate-icons.mjs
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Resvg } from '@resvg/resvg-js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const publicIcons = join(__dirname, '../../public/app-icons');
const srcLib = join(__dirname, '../../src/lib');
mkdirSync(publicIcons, { recursive: true });

/** Identical to Logo.tsx / favicon.svg */
const CF_CLOUD =
  'M16.5088 16.8447c.1475-.5068.0908-.9707-.1553-1.3154-.2246-.3164-.6045-.499-1.0615-.5205l-8.6592-.1123a.1559.1559 0 0 1-.1333-.0713c-.0283-.042-.0351-.0986-.021-.1553.0278-.084.1123-.1484.2036-.1562l8.7359-.1123c1.0351-.0489 2.1601-.8868 2.5537-1.9136l.499-1.3013c.0215-.0561.0293-.1128.0147-.168-.5625-2.5463-2.835-4.4453-5.5499-4.4453-2.5039 0-4.6284 1.6177-5.3876 3.8614-.4927-.3658-1.1187-.5625-1.794-.499-1.2026.119-2.1665 1.083-2.2861 2.2856-.0283.31-.0069.6128.0635.894C1.5683 13.171 0 14.7754 0 16.752c0 .1748.0142.3515.0352.5273.0141.083.0844.1475.1689.1475h15.9814c.0909 0 .1758-.0645.2032-.1553l.12-.4268zm2.7568-5.5634c-.0771 0-.1611 0-.2383.0112-.0566 0-.1054.0415-.127.0976l-.3378 1.1744c-.1475.5068-.0918.9707.1543 1.3164.2256.3164.6055.498 1.0625.5195l1.8437.1133c.0557 0 .1055.0263.1329.0703.0283.043.0351.1074.0214.1562-.0283.084-.1132.1485-.204.1553l-1.921.1123c-1.041.0488-2.1582.8867-2.5527 1.914l-.1406.3585c-.0283.0713.0215.1416.0986.1416h6.5977c.0771 0 .1474-.0489.169-.126.1122-.4082.1757-.837.1757-1.2803 0-2.6025-2.125-4.727-4.7344-4.727';

/**
 * Transparent canvas + CF mark only (matches in-app Logo).
 * Light theme uses deeper green for contrast on light taskbars.
 */
function svgFor(theme, size) {
  const cloud = theme === 'light' ? '#1f8a4c' : '#5fad7a';

  // ~8% padding so mark stays large at 16–32px
  const pad = size * 0.08;
  const scale = (size - pad * 2) / 24;
  const tx = pad;
  const ty = pad + size * 0.04;

  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 ${size} ${size}">
  <g transform="translate(${tx} ${ty}) scale(${scale})">
    <path fill="${cloud}" fill-rule="nonzero" d="${CF_CLOUD}"/>
  </g>
</svg>`;
}

function render(theme, size) {
  const svg = svgFor(theme, size);
  return new Resvg(svg, { fitTo: { mode: 'width', value: size } }).render().asPng();
}

function buildIco(pngBuffers, sizes) {
  const count = pngBuffers.length;
  const header = Buffer.alloc(6 + 16 * count);
  header.writeUInt16LE(0, 0);
  header.writeUInt16LE(1, 2);
  header.writeUInt16LE(count, 4);
  let offset = 6 + 16 * count;
  const parts = [header];
  for (let i = 0; i < count; i++) {
    const png = pngBuffers[i];
    const size = sizes[i];
    const e = 6 + i * 16;
    header.writeUInt8(size >= 256 ? 0 : size, e);
    header.writeUInt8(size >= 256 ? 0 : size, e + 1);
    header.writeUInt8(0, e + 2);
    header.writeUInt8(0, e + 3);
    header.writeUInt16LE(1, e + 4);
    header.writeUInt16LE(32, e + 6);
    header.writeUInt32LE(png.length, e + 8);
    header.writeUInt32LE(offset, e + 12);
    parts.push(png);
    offset += png.length;
  }
  return Buffer.concat(parts);
}

function writePng(path, buf) {
  writeFileSync(path, buf);
  console.log('wrote', path.replace(/.*[\\/](icons|app-icons|lib)[\\/]/, '$1/'), `(${buf.length}b)`);
}

const icoSizes = [16, 24, 32, 48, 64, 128, 256];

for (const [name, size] of [
  ['32x32.png', 32],
  ['128x128.png', 128],
  ['128x128@2x.png', 256],
  ['icon-256.png', 256],
  ['icon.png', 512],
]) {
  writePng(join(__dirname, name), render('dark', size));
}

writeFileSync(
  join(__dirname, 'icon.ico'),
  buildIco(
    icoSizes.map((s) => render('dark', s)),
    icoSizes,
  ),
);
writeFileSync(
  join(__dirname, 'icon-light.ico'),
  buildIco(
    icoSizes.map((s) => render('light', s)),
    icoSizes,
  ),
);
console.log('wrote icon.ico + icon-light.ico');

const assets = {};
for (const theme of ['dark', 'light']) {
  for (const size of [32, 48, 128, 256]) {
    const buf = render(theme, size);
    writePng(join(publicIcons, `icon-${theme}-${size}.png`), buf);
    assets[`${theme}_${size}`] = buf.toString('base64');
  }
}

writeFileSync(
  join(srcLib, 'embeddedIcons.ts'),
  `/* AUTO-GENERATED by generate-icons.mjs — do not edit */
export const EMBEDDED_ICONS = {
  dark_256: '${assets.dark_256}',
  dark_128: '${assets.dark_128}',
  light_256: '${assets.light_256}',
  light_128: '${assets.light_128}',
} as const;
`,
);
console.log('wrote embeddedIcons.ts');

writeFileSync(join(__dirname, 'icon.icns'), render('dark', 256));
writeFileSync(join(__dirname, 'app-icon.svg'), svgFor('dark', 512));
console.log('done — transparent Cloudflare mark');
